package com.behsazan.schemaforge.dialect.db2zos;

import com.behsazan.schemaforge.dialect.Dialect;
import com.behsazan.schemaforge.dialect.DialectFeature;
import com.behsazan.schemaforge.dialect.NumericMappingStrategy;
import com.behsazan.schemaforge.domain.enums.ReferentialAction;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.valueobject.Identifier;

import java.util.Objects;
import java.util.Set;

/** Db2 for z/OS type, identifier, expression and DDL rendering rules. */
public final class Db2ZosDialect implements Dialect {
    private static final Set<DialectFeature> FEATURES = Set.of(
            DialectFeature.SEQUENCE,
            DialectFeature.IDENTITY_COLUMN,
            DialectFeature.GENERATED_COLUMN,
            DialectFeature.TABLE_COMMENT,
            DialectFeature.COLUMN_COMMENT,
            DialectFeature.GRANT);

    private final Db2ZosTypeMapper typeMapper;
    private final Db2ZosIdentifierRenderer identifierRenderer;
    private final Db2ZosExpressionMapper expressionMapper;

    public Db2ZosDialect() {
        this(NumericMappingStrategy.SAFE);
    }

    public Db2ZosDialect(NumericMappingStrategy strategy) {
        this.typeMapper = new Db2ZosTypeMapper(strategy);
        this.identifierRenderer = new Db2ZosIdentifierRenderer();
        this.expressionMapper = new Db2ZosExpressionMapper();
    }

    @Override
    public Set<DialectFeature> supportedFeatures() {
        return FEATURES;
    }

    @Override
    public String sqlType(Column column) {
        Objects.requireNonNull(column, "column must not be null");
        return typeMapper.map(column.dataType());
    }

    @Override
    public String quote(Identifier identifier) {
        return identifierRenderer.render(identifier);
    }

    @Override
    public String expression(String expression) {
        return expressionMapper.map(expression);
    }

    @Override
    public String defaultClause(Column column) {
        return " DEFAULT " + expression(column.defaultValue().expression());
    }

    @Override
    public String generatedColumnClause(Column column) {
        return " GENERATED ALWAYS AS (" + expression(column.generatedExpression()) + ")";
    }

    @Override
    public String identityClause(Column column) {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String sequenceCacheClause(Integer cacheSize) {
        return cacheSize == null || cacheSize == 0 ? " NO CACHE" : " CACHE " + cacheSize;
    }

    @Override
    public String sequenceCycleClause(boolean cycle) {
        return cycle ? " CYCLE" : " NO CYCLE";
    }

    @Override
    public String referentialActionClause(String clause, ReferentialAction action) {
        if (action == null || action == ReferentialAction.NO_ACTION) {
            return "";
        }
        if ("ON UPDATE".equalsIgnoreCase(clause)) {
            if (action == ReferentialAction.RESTRICT) {
                // Db2 z/OS has no ON UPDATE clause; dependent parent-key updates are restricted.
                return "";
            }
            throw new UnsupportedOperationException(
                    "Db2 z/OS does not support " + clause + " " + action);
        }
        if (action == ReferentialAction.SET_DEFAULT) {
            throw new UnsupportedOperationException(
                    "Db2 z/OS does not support ON DELETE SET DEFAULT");
        }
        return Dialect.super.referentialActionClause(clause, action);
    }

    @Override
    public String tableTablespaceClause(String tablespace) {
        if (tablespace == null || tablespace.isBlank()) {
            return "";
        }
        String[] parts = tablespace.trim().split("\\.", -1);
        if (parts.length == 1) {
            return " IN " + identifierRenderer.render(Identifier.of(parts[0]));
        }
        if (parts.length == 2 && !parts[0].isBlank() && !parts[1].isBlank()) {
            return " IN " + identifierRenderer.render(Identifier.of(parts[0]))
                    + "." + identifierRenderer.render(Identifier.of(parts[1]));
        }
        throw new IllegalArgumentException(
                "Db2 z/OS TABLESPACE must be TABLESPACE or DATABASE.TABLESPACE: " + tablespace);
    }

    /** Db2 index spaces are controlled by CREATE INDEX storage clauses, not TABLESPACE. */
    @Override
    public String indexTablespaceClause(String tablespace) {
        return "";
    }

    @Override
    public String scriptPreamble(String source, String schemaName) {
        String nl = System.lineSeparator();
        return "-- ==============================================================" + nl
                + "-- SchemaForge Offline Db2 for z/OS DDL" + nl
                + (source == null ? "" : "-- Source File : " + source + nl)
                + "-- Schema      : " + schemaName + nl
                + "-- ==============================================================";
    }
}
