package com.behsazan.schemaforge.dialect.db2zos;

import com.behsazan.schemaforge.dialect.Dialect;
import com.behsazan.schemaforge.dialect.DialectFeature;
import com.behsazan.schemaforge.dialect.NumericMappingStrategy;
import com.behsazan.schemaforge.domain.enums.ReferentialAction;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.model.Index;
import com.behsazan.schemaforge.domain.valueobject.Identifier;

import java.util.Locale;
import java.util.Objects;
import java.util.Set;

/** Db2 for z/OS type, identifier, expression and DDL rendering rules. */
public final class Db2ZosDialect implements Dialect {
    private static final Set<DialectFeature> FEATURES = Set.of(
            DialectFeature.SEQUENCE,
            DialectFeature.IDENTITY_COLUMN,
            DialectFeature.GENERATED_COLUMN,
            DialectFeature.TABLE_COMMENT,
            DialectFeature.COLUMN_COMMENT,
            DialectFeature.GRANT);

    private final NumericMappingStrategy numericMappingStrategy;
    private final Db2ZosTypeMapper typeMapper;
    private final Db2ZosIdentifierRenderer identifierRenderer;
    private final Db2ZosExpressionMapper expressionMapper;

    public Db2ZosDialect() {
        this(NumericMappingStrategy.SAFE);
    }

    public Db2ZosDialect(NumericMappingStrategy strategy) {
        this.numericMappingStrategy = Objects.requireNonNull(strategy, "strategy must not be null");
        this.typeMapper = new Db2ZosTypeMapper(strategy);
        this.identifierRenderer = new Db2ZosIdentifierRenderer();
        this.expressionMapper = new Db2ZosExpressionMapper();
    }

    @Override
    public NumericMappingStrategy numericMappingStrategy() {
        return numericMappingStrategy;
    }

    @Override
    public Set<DialectFeature> supportedFeatures() {
        return FEATURES;
    }

    @Override
    public String sqlType(Column column) {
        Objects.requireNonNull(column, "column must not be null");
        return typeMapper.map(column.dataType());
    }

    @Override
    public String quote(Identifier identifier) {
        return identifierRenderer.render(identifier);
    }

    @Override
    public String expression(String expression) {
        return expressionMapper.map(expression);
    }

    @Override
    public String defaultClause(Column column) {
        return " WITH DEFAULT " + expression(column.defaultValue().expression());
    }

    @Override
    public String generatedColumnClause(Column column) {
        return " GENERATED ALWAYS AS (" + expression(column.generatedExpression()) + ")";
    }

    @Override
    public String identityClause(Column column) {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String sequenceCacheClause(Integer cacheSize) {
        return cacheSize == null || cacheSize == 0 ? " NO CACHE" : " CACHE " + cacheSize;
    }

    @Override
    public String sequenceCycleClause(boolean cycle) {
        return cycle ? " CYCLE" : " NO CYCLE";
    }

    @Override
    public String referentialActionClause(String clause, ReferentialAction action) {
        if (action == null || action == ReferentialAction.NO_ACTION) {
            return "";
        }
        if ("ON UPDATE".equalsIgnoreCase(clause)) {
            if (action == ReferentialAction.RESTRICT) {
                // Db2 z/OS has no ON UPDATE clause; dependent parent-key updates are restricted.
                return "";
            }
            throw new UnsupportedOperationException(
                    "Db2 z/OS does not support " + clause + " " + action);
        }
        if (action == ReferentialAction.SET_DEFAULT) {
            throw new UnsupportedOperationException(
                    "Db2 z/OS does not support ON DELETE SET DEFAULT");
        }
        return Dialect.super.referentialActionClause(clause, action);
    }

    @Override
    public boolean requiresExplicitConstraintIndexes() {
        return true;
    }

    @Override
    public String tableTablespaceClause(String tablespace) {
        if (tablespace == null || tablespace.isBlank()) {
            return "";
        }
        String[] parts = tablespace.trim().split("\\.", -1);
        if (parts.length == 1) {
            return " IN " + identifierRenderer.render(Identifier.of(parts[0]));
        }
        if (parts.length == 2 && !parts[0].isBlank() && !parts[1].isBlank()) {
            return " IN " + identifierRenderer.render(Identifier.of(parts[0]))
                    + "." + identifierRenderer.render(Identifier.of(parts[1]));
        }
        throw new IllegalArgumentException(
                "Db2 z/OS TABLESPACE must be TABLESPACE or DATABASE.TABLESPACE: " + tablespace);
    }

    /** Db2 index spaces are controlled by CREATE INDEX storage clauses, not TABLESPACE. */
    @Override
    public String indexTablespaceClause(String tablespace) {
        return "";
    }

    @Override
    public String tableTailWithPhysical(String activePlacementClause, String physicalCommentBlock) {
        String placement = activePlacementClause == null ? "" : activePlacementClause;
        String physical = physicalCommentBlock == null ? "" : physicalCommentBlock;
        return placement + physical;
    }


    @Override
    public String indexBuildTail(Index index) {
        if (index == null || index.buildOptions().isEmpty()) return "";

        String define = buildOption(index, "DEFINE", "DB2_DEFINE", "DB2_INDEX_DEFINE");
        String defer = buildOption(index, "DEFER", "DB2_DEFER", "DB2_INDEX_DEFER");
        StringBuilder tail = new StringBuilder();

        if (!define.isBlank() && isBooleanToken(define)) {
            boolean defineNo = isNo(define);
            if (!defineNo || hasExplicitStogroup(index)) {
                tail.append(" DEFINE " ).append(isYes(define) ? "YES" : "NO");
            }
        }
        if (!defer.isBlank() && isBooleanToken(defer)) {
            tail.append(" DEFER " ).append(isYes(defer) ? "YES" : "NO");
        }
        return tail.toString();
    }

    @Override
    public String indexBuildReviewComment(Index index) {
        if (index == null || index.buildOptions().isEmpty()) return "";

        String define = buildOption(index, "DEFINE", "DB2_DEFINE", "DB2_INDEX_DEFINE");
        String defer = buildOption(index, "DEFER", "DB2_DEFER", "DB2_INDEX_DEFER");
        String nl = System.lineSeparator();
        StringBuilder out = new StringBuilder();

        if (!define.isBlank() && !isBooleanToken(define)) {
            appendBuildComment(out, nl, "-- [INDEX BUILD ISSUE][DB2/ZOS] DEFINE=" + define
                    + " is invalid; expected YES/NO. The build directive was not emitted.");
        } else if (isNo(define) && !hasExplicitStogroup(index)) {
            appendBuildComment(out, nl, "-- [INDEX BUILD ISSUE][DB2/ZOS] DEFINE=NO requires explicit DB2_INDEX_STOGROUP/INDEX_STOGROUP evidence in SchemaForge; Db2 documents DEFINE NO for Db2-managed data sets using STOGROUP, so the directive was not emitted.");
        } else if (isNo(define)) {
            appendBuildComment(out, nl, "-- [INDEX BUILD REVIEW][DB2/ZOS] DEFINE NO is explicit; underlying index data sets are deferred and the documented clone/external-load/temporary-table restrictions must be reviewed.");
        }

        if (!defer.isBlank() && !isBooleanToken(defer)) {
            appendBuildComment(out, nl, "-- [INDEX BUILD ISSUE][DB2/ZOS] DEFER=" + defer
                    + " is invalid; expected YES/NO. The build directive was not emitted.");
        } else if (isYes(defer)) {
            appendBuildComment(out, nl, "-- [INDEX BUILD REVIEW][DB2/ZOS] DEFER YES is explicit; on a populated table the index is placed in rebuild-pending status and requires REBUILD INDEX.");
        }
        return out.toString();
    }

    private String buildOption(Index index, String... keys) {
        for (String key : keys) {
            for (var entry : index.buildOptions().entrySet()) {
                if (entry.getKey().equalsIgnoreCase(key) && entry.getValue() != null) {
                    String value = entry.getValue().trim().toUpperCase(Locale.ROOT);
                    if (!value.isBlank()) return value;
                }
            }
        }
        return "";
    }

    private boolean hasExplicitStogroup(Index index) {
        for (var entry : index.physicalOptions().entrySet()) {
            if ((entry.getKey().equalsIgnoreCase("DB2_INDEX_STOGROUP")
                    || entry.getKey().equalsIgnoreCase("INDEX_STOGROUP"))
                    && entry.getValue() != null && !entry.getValue().trim().isBlank()) {
                return true;
            }
        }
        return false;
    }

    private boolean isBooleanToken(String value) {
        return value.isBlank() || isYes(value) || isNo(value);
    }

    private boolean isYes(String value) {
        return Set.of("YES", "ON", "TRUE", "1").contains(value);
    }

    private boolean isNo(String value) {
        return Set.of("NO", "OFF", "FALSE", "0").contains(value);
    }

    private void appendBuildComment(StringBuilder out, String nl, String line) {
        if (out.length() > 0) out.append(nl);
        out.append(line);
    }

    @Override
    public String scriptPreamble(String source, String schemaName) {
        String nl = System.lineSeparator();
        return "-- ==============================================================" + nl
                + "-- SchemaForge Offline Db2 for z/OS DDL" + nl
                + (source == null ? "" : "-- Source File : " + source + nl)
                + "-- Schema      : " + schemaName + nl
                + "-- ==============================================================";
    }

    @Override
    public String schemaBootstrapStatement(Identifier schemaName) {
        Objects.requireNonNull(schemaName, "schemaName must not be null");
        String schema = quote(schemaName);
        String nl = System.lineSeparator();
        return "-- [SCHEMA BOOTSTRAP] Db2 for z/OS CREATE SCHEMA must be processed" + nl
                + "-- by the DSNHSP schema processor and is not executed in this ordinary DDL file." + nl
                + "-- DSNHSP template: CREATE SCHEMA AUTHORIZATION " + schema + nl
                + "-- Ensure the execution authorization ID has the required CREATEIN/DROPIN" + nl
                + "-- schema privileges and table/database authorities before running this script.";
    }
}
