package com.behsazan.schemaforge.dialect.db2luw;

import com.behsazan.schemaforge.dialect.Dialect;
import com.behsazan.schemaforge.dialect.DialectFeature;
import com.behsazan.schemaforge.dialect.NumericMappingStrategy;
import com.behsazan.schemaforge.domain.enums.ReferentialAction;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.valueobject.Identifier;

import java.util.Objects;
import java.util.Set;

/** Db2 LUW type, identifier, expression and core DDL rendering rules. */
public final class Db2LuwDialect implements Dialect {
    private static final Set<DialectFeature> FEATURES = Set.of(
            DialectFeature.SEQUENCE,
            DialectFeature.IDENTITY_COLUMN,
            DialectFeature.GENERATED_COLUMN,
            DialectFeature.TABLE_COMMENT,
            DialectFeature.COLUMN_COMMENT,
            DialectFeature.GRANT);

    private final NumericMappingStrategy numericMappingStrategy;
    private final Db2LuwTypeMapper typeMapper;
    private final Db2LuwIdentifierRenderer identifierRenderer;
    private final Db2LuwExpressionMapper expressionMapper;

    public Db2LuwDialect() {
        this(NumericMappingStrategy.SAFE);
    }

    public Db2LuwDialect(NumericMappingStrategy strategy) {
        this.numericMappingStrategy = Objects.requireNonNull(strategy, "strategy must not be null");
        this.typeMapper = new Db2LuwTypeMapper(strategy);
        this.identifierRenderer = new Db2LuwIdentifierRenderer();
        this.expressionMapper = new Db2LuwExpressionMapper();
    }

    @Override
    public NumericMappingStrategy numericMappingStrategy() {
        return numericMappingStrategy;
    }

    @Override
    public Set<DialectFeature> supportedFeatures() {
        return FEATURES;
    }

    @Override
    public String sqlType(Column column) {
        Objects.requireNonNull(column, "column must not be null");
        return typeMapper.map(column.dataType());
    }

    @Override
    public String quote(Identifier identifier) {
        return identifierRenderer.render(identifier);
    }

    @Override
    public String expression(String expression) {
        return expressionMapper.map(expression);
    }

    @Override
    public String defaultClause(Column column) {
        Objects.requireNonNull(column, "column must not be null");
        String sourceExpression = column.defaultValue().expression();
        if (expressionMapper.containsNextValueReference(sourceExpression)) {
            if (column.identity()) {
                return identityClause(column)
                        + " /* [DB2/LUW IDENTITY ADAPTATION][DB2LUW-SEQ-DEFAULT-002] "
                        + "Source sequence NEXTVAL default mapped to native Db2 LUW identity; "
                        + "the canonical sequence object is still emitted separately. */";
            }
            String mapped = safeInlineComment(expression(sourceExpression));
            return " /* [DB2/LUW DEFAULT REVIEW][DB2LUW-SEQ-DEFAULT-001] "
                    + "Db2 LUW does not allow a sequence NEXT VALUE expression as a column DEFAULT. "
                    + "Source intent was: " + mapped + ". The sequence is still created, but this "
                    + "column has no automatic sequence default. Use " + mapped
                    + " explicitly in DML, or add a DBA-reviewed BEFORE INSERT trigger if automatic "
                    + "assignment is required. */";
        }
        return " WITH DEFAULT " + expression(sourceExpression);
    }

    private String safeInlineComment(String value) {
        return value == null ? "" : value
                .replace("*/", "* /")
                .replace('\r', ' ')
                .replace('\n', ' ')
                .trim();
    }

    @Override
    public String inlineColumnConstraintClause(com.behsazan.schemaforge.domain.model.Table table, Column column) {
        Objects.requireNonNull(table, "table must not be null");
        Objects.requireNonNull(column, "column must not be null");
        if (!column.nullable()) {
            return "";
        }
        boolean primaryKeyColumn = table.primaryKey()
                .map(primaryKey -> primaryKey.columns().stream()
                        .anyMatch(keyColumn -> keyColumn.normalized().equals(column.name().normalized())))
                .orElse(false);
        if (!primaryKeyColumn) {
            return "";
        }
        return " NOT NULL /* [DB2/LUW PK NULLABILITY ADAPTATION][DB2LUW-PK-NULL-001] "
                + "Db2 LUW requires every PRIMARY KEY column to be explicitly NOT NULL. "
                + "The canonical nullable flag was preserved; only target DDL nullability was adapted. */";
    }

    @Override
    public String generatedColumnClause(Column column) {
        return " GENERATED ALWAYS AS (" + expression(column.generatedExpression()) + ")";
    }

    @Override
    public String identityClause(Column column) {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String sequenceCacheClause(Integer cacheSize) {
        return cacheSize == null || cacheSize == 0 ? " NO CACHE" : " CACHE " + cacheSize;
    }

    @Override
    public String sequenceCycleClause(boolean cycle) {
        return cycle ? " CYCLE" : " NO CYCLE";
    }

    @Override
    public String referentialActionClause(String clause, ReferentialAction action) {
        if (action == null || action == ReferentialAction.NO_ACTION) {
            return "";
        }
        if ("ON UPDATE".equalsIgnoreCase(clause)) {
            if (action == ReferentialAction.RESTRICT) {
                return " ON UPDATE RESTRICT";
            }
            throw new UnsupportedOperationException(
                    "Db2 LUW supports only NO ACTION or RESTRICT for ON UPDATE");
        }
        if (action == ReferentialAction.SET_DEFAULT) {
            throw new UnsupportedOperationException("Db2 LUW does not support ON DELETE SET DEFAULT");
        }
        return Dialect.super.referentialActionClause(clause, action);
    }

    @Override
    public String tableTablespaceClause(String tablespace) {
        if (tablespace == null || tablespace.isBlank()) return "";
        return " IN " + renderTablespace(tablespace);
    }

    @Override
    public String indexTablespaceClause(String tablespace) {
        if (tablespace == null || tablespace.isBlank()) return "";
        return " IN " + renderTablespace(tablespace);
    }

    private String renderTablespace(String tablespace) {
        String[] parts = tablespace.trim().split("\\.", -1);
        if (parts.length == 1 && !parts[0].isBlank()) {
            return quote(Identifier.of(parts[0]));
        }
        if (parts.length == 2 && !parts[0].isBlank() && !parts[1].isBlank()) {
            return quote(Identifier.of(parts[0])) + "." + quote(Identifier.of(parts[1]));
        }
        throw new IllegalArgumentException(
                "Db2 LUW TABLESPACE must be TABLESPACE or DATABASE.TABLESPACE: " + tablespace);
    }

    @Override
    public String scriptPreamble(String source, String schemaName) {
        String nl = System.lineSeparator();
        return "-- ==============================================================" + nl
                + "-- SchemaForge Offline Db2 LUW DDL" + nl
                + (source == null ? "" : "-- Source File : " + source + nl)
                + "-- Schema      : " + schemaName + nl
                + "-- ==============================================================";
    }

    @Override
    public String infrastructureProvisioningTemplate(Identifier schemaName) {
        Objects.requireNonNull(schemaName, "schemaName must not be null");
        String nl = System.lineSeparator();
        return "-- [INFRASTRUCTURE TEMPLATE][DB2/LUW] DBA review required." + nl
                + "-- SchemaForge never guesses table-space containers, page size, buffer pools or storage paths." + nl
                + "-- CREATE TABLESPACE <TABLESPACE> ...;" + nl
                + "-- Optional: CREATE BUFFERPOOL <BUFFERPOOL> ...;";
    }

    @Override
    public String schemaBootstrapStatement(Identifier schemaName) {
        Objects.requireNonNull(schemaName, "schemaName must not be null");
        String schema = quote(schemaName);
        String nl = System.lineSeparator();
        return "-- [SCHEMA BOOTSTRAP][DB2/LUW] Ensure schema exists before application DDL." + nl
                + "-- CREATE SCHEMA " + schema + ";" + nl
                + "-- If an explicit owner is required: CREATE SCHEMA " + schema + " AUTHORIZATION <AUTHID>;";
    }
}
