package com.behsazan.schemaforge.dialect.postgresql;

import com.behsazan.schemaforge.dialect.Dialect;
import com.behsazan.schemaforge.dialect.DialectFeature;
import com.behsazan.schemaforge.dialect.NumericMappingStrategy;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.valueobject.Identifier;
import com.behsazan.schemaforge.domain.valueobject.QualifiedName;

import java.util.Locale;
import java.util.Objects;
import java.util.Set;

/** PostgreSQL-specific type, identifier and DDL rendering rules. */
public final class PostgreSqlDialect implements Dialect {
    private final NumericMappingStrategy numericMappingStrategy;
    private final PostgreSqlTypeMapper typeMapper;
    private static final PostgreSqlExpressionMapper EXPRESSION_MAPPER = new PostgreSqlExpressionMapper();
    private static final PostgreSqlIdentifierRenderer IDENTIFIER_RENDERER = new PostgreSqlIdentifierRenderer();

    public PostgreSqlDialect() {
        this(NumericMappingStrategy.SAFE);
    }

    public PostgreSqlDialect(NumericMappingStrategy strategy) {
        this.numericMappingStrategy = Objects.requireNonNull(strategy, "strategy must not be null");
        this.typeMapper = new PostgreSqlTypeMapper(strategy);
    }

    private static final Set<DialectFeature> FEATURES = Set.of(
            DialectFeature.SEQUENCE,
            DialectFeature.IDENTITY_COLUMN,
            DialectFeature.GENERATED_COLUMN,
            DialectFeature.TABLE_COMMENT,
            DialectFeature.COLUMN_COMMENT,
            DialectFeature.GRANT,
            DialectFeature.INDEX_INCLUDE,
            DialectFeature.PARTIAL_INDEX,
            DialectFeature.EXPRESSION_INDEX,
            DialectFeature.DEFERRABLE_CONSTRAINT);

    @Override
    public NumericMappingStrategy numericMappingStrategy() {
        return numericMappingStrategy;
    }

    @Override
    public Set<DialectFeature> supportedFeatures() {
        return FEATURES;
    }


    @Override
    public String sqlType(Column column) {
        Objects.requireNonNull(column, "column must not be null");
        return typeMapper.map(column.dataType());
    }

    @Override
    public String quote(Identifier identifier) {
        Objects.requireNonNull(identifier, "identifier must not be null");
        return IDENTIFIER_RENDERER.render(identifier);
    }


    @Override
    public String expression(String expression) {
        return EXPRESSION_MAPPER.map(expression);
    }

    @Override
    public String defaultClause(Column column) {
        return " DEFAULT " + expression(column.defaultValue().expression());
    }

    @Override
    public String generatedColumnClause(Column column) {
        return " GENERATED ALWAYS AS (" + expression(column.generatedExpression()) + ") STORED";
    }

    @Override
    public String identityClause(Column column) {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String sequenceCacheClause(Integer cacheSize) {
        return " CACHE " + (cacheSize == null || cacheSize == 0 ? 1 : cacheSize);
    }

    @Override
    public String sequenceCycleClause(boolean cycle) {
        return cycle ? " CYCLE" : " NO CYCLE";
    }

    @Override
    public String sequenceTail() {
        return "";
    }

    @Override
    public String constraintValidationClause() {
        return "";
    }


    @Override
    public String tableTablespaceClause(String tablespace) {
        if (tablespace == null || tablespace.isBlank()) return "";
        return " TABLESPACE " + IDENTIFIER_RENDERER.render(Identifier.of(tablespace.trim()));
    }

    @Override
    public String indexTablespaceClause(String tablespace) {
        if (tablespace == null || tablespace.isBlank()) return "";
        return " TABLESPACE " + IDENTIFIER_RENDERER.render(Identifier.of(tablespace.trim()));
    }

    @Override
    public String qualifyIndexName(QualifiedName tableName, String renderedIndexName) {
        // PostgreSQL creates an index in the same schema as its table and does not allow
        // a schema-qualified index name in CREATE INDEX.
        return renderedIndexName;
    }

    @Override
    public String primaryKeyConstraint(String constraintName, String tableName, String columns,
                                       String qualifiedIndexName, String indexTablespace, boolean deferrable, boolean initiallyDeferred) {
        return "CONSTRAINT " + constraintName + " PRIMARY KEY (" + columns + ")"
                + constraintIndexTablespaceClause(indexTablespace)
                + deferrabilityClause(deferrable, initiallyDeferred);
    }

    @Override
    public String uniqueConstraint(String constraintName, String tableName, String columns,
                                   String qualifiedIndexName, String indexTablespace, boolean deferrable, boolean initiallyDeferred) {
        return "ALTER TABLE " + tableName
                + " ADD CONSTRAINT " + constraintName + " UNIQUE(" + columns + ")"
                + constraintIndexTablespaceClause(indexTablespace)
                + deferrabilityClause(deferrable, initiallyDeferred)
                + statementTerminator();
    }

    private String constraintIndexTablespaceClause(String tablespace) {
        if (tablespace == null || tablespace.isBlank()) {
            return "";
        }
        return " USING INDEX TABLESPACE "
                + IDENTIFIER_RENDERER.render(Identifier.of(tablespace.trim()));
    }

    @Override
    public String primaryKeyConstraintWithPhysical(
            String constraintName, String tableName, String columns,
            String qualifiedIndexName, String indexTablespace, String physicalIndexComment,
            boolean deferrable, boolean initiallyDeferred) {
        return "CONSTRAINT " + constraintName + " PRIMARY KEY (" + columns + ")"
                + physicalIndexComment
                + constraintIndexTablespaceClause(indexTablespace)
                + deferrabilityClause(deferrable, initiallyDeferred);
    }

    @Override
    public String uniqueConstraintWithPhysical(
            String constraintName, String tableName, String columns,
            String qualifiedIndexName, String indexTablespace, String physicalIndexComment,
            boolean deferrable, boolean initiallyDeferred) {
        return "ALTER TABLE " + tableName
                + " ADD CONSTRAINT " + constraintName + " UNIQUE(" + columns + ")"
                + physicalIndexComment
                + constraintIndexTablespaceClause(indexTablespace)
                + deferrabilityClause(deferrable, initiallyDeferred)
                + statementTerminator();
    }

    @Override
    public String indexTailWithPhysical(
            String includeColumns, String physicalIndexComment,
            String indexTablespace, String predicate) {
        return indexIncludeClause(includeColumns)
                + physicalIndexComment
                + indexTablespaceClause(indexTablespace)
                + partialIndexClause(predicate);
    }

    @Override
    public String scriptPreamble(String source, String schemaName) {
        String nl = System.lineSeparator();
        return "-- ==============================================================" + nl
                + "-- SchemaForge Offline PostgreSQL DDL" + nl
                + (source == null ? "" : "-- Source File : " + source + nl)
                + "-- Schema      : " + schemaName.toLowerCase(Locale.ROOT) + nl
                + "-- ==============================================================" + nl
                + "\\encoding UTF8" + nl
                + "\\set ON_ERROR_STOP on";
    }

    @Override
    public String warningLine(String text) {
        return "-- " + text;
    }

    @Override
    public String schemaBootstrapStatement(Identifier schemaName) {
        Objects.requireNonNull(schemaName, "schemaName must not be null");
        return "CREATE SCHEMA IF NOT EXISTS " + quote(schemaName)
                + " AUTHORIZATION CURRENT_USER" + statementTerminator();
    }
}
