package com.behsazan.schemaforge.dialect;

import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.valueobject.Identifier;

import java.util.Set;

/**
 * DBMS-specific SQL rendering contract used by the DBMS-neutral DDL generator.
 * Any syntax that varies between database engines belongs here, not in DdlGenerator.
 */
public interface Dialect {
    /** Returns the optional DDL capabilities implemented by this dialect. */
    default Set<DialectFeature> supportedFeatures() {
        return Set.of();
    }

    default boolean supports(DialectFeature feature) {
        return supportedFeatures().contains(feature);
    }

    default void require(DialectFeature feature) {
        if (!supports(feature)) {
            throw new UnsupportedOperationException(
                    name() + " dialect does not support " + feature);
        }
    }

    String sqlType(Column column);

    String quote(Identifier identifier);

    default String name() {
        return getClass().getSimpleName().replace("Dialect", "");
    }

    default String statementTerminator() {
        return ";";
    }

    default String generatedColumnClause(Column column) {
        return " AS (" + column.generatedExpression() + ")";
    }

    default String identityClause(Column column) {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    default String defaultClause(Column column) {
        return " DEFAULT " + expression(column.defaultValue().expression());
    }

    /** Renders a DBMS-specific scalar expression used by defaults, checks and generated columns. */
    default String expression(String expression) {
        return expression;
    }

    default String sequenceCacheClause(Integer cacheSize) {
        return cacheSize == null || cacheSize == 0 ? " CACHE 1" : " CACHE " + cacheSize;
    }

    default String sequenceCycleClause(boolean cycle) {
        return cycle ? " CYCLE" : " NO CYCLE";
    }

    default String sequenceTail() {
        return "";
    }

    default String constraintValidationClause() {
        return "";
    }

    default String tableTablespaceClause(String tablespace) {
        return tablespace == null || tablespace.isBlank() ? "" : " TABLESPACE " + tablespace.trim();
    }

    default String indexTablespaceClause(String tablespace) {
        return tablespace == null || tablespace.isBlank() ? "" : " TABLESPACE " + tablespace.trim();
    }

    default String primaryKeyConstraint(String constraintName, String tableName, String columns,
                                        String qualifiedIndexName, String indexTablespace, boolean deferrable, boolean initiallyDeferred) {
        return "CONSTRAINT " + constraintName + " PRIMARY KEY (" + columns + ")"
                + deferrabilityClause(deferrable, initiallyDeferred);
    }

    default String uniqueConstraint(String constraintName, String tableName, String columns,
                                    String qualifiedIndexName, String indexTablespace, boolean deferrable, boolean initiallyDeferred) {
        return "ALTER TABLE " + tableName
                + " ADD CONSTRAINT " + constraintName
                + " UNIQUE(" + columns + ")"
                + deferrabilityClause(deferrable, initiallyDeferred)
                + statementTerminator();
    }

    default String deferrabilityClause(boolean deferrable, boolean initiallyDeferred) {
        if (!deferrable) return "";
        require(DialectFeature.DEFERRABLE_CONSTRAINT);
        return initiallyDeferred ? " DEFERRABLE INITIALLY DEFERRED" : " DEFERRABLE INITIALLY IMMEDIATE";
    }

    default String indexIncludeClause(String columns) {
        if (columns == null || columns.isBlank()) return "";
        require(DialectFeature.INDEX_INCLUDE);
        return " INCLUDE (" + columns + ")";
    }

    default String partialIndexClause(String predicate) {
        if (predicate == null || predicate.isBlank()) return "";
        require(DialectFeature.PARTIAL_INDEX);
        return " WHERE " + expression(predicate);
    }

    default String scriptPreamble(String source, String schemaName) {
        String nl = System.lineSeparator();
        return "-- ==============================================================" + nl
                + "-- SchemaForge Offline " + name() + " DDL" + nl
                + (source == null ? "" : "-- Source File : " + source + nl)
                + "-- Schema      : " + schemaName + nl
                + "-- ==============================================================";
    }

    default String warningLine(String text) {
        return "-- " + text;
    }
}
