package com.behsazan.schemaforge.domain.enums;
public enum ObjectType { SCHEMA, TABLE, COLUMN, PRIMARY_KEY, FOREIGN_KEY, UNIQUE_KEY, CHECK_CONSTRAINT, INDEX, SEQUENCE, VIEW, SYNONYM, TRIGGER, PROCEDURE, FUNCTION, PACKAGE }
