package com.behsazan.schemaforge;

import com.behsazan.schemaforge.dialect.db2luw.Db2LuwDialect;
import com.behsazan.schemaforge.domain.enums.IndexType;
import com.behsazan.schemaforge.domain.enums.ReferentialAction;
import com.behsazan.schemaforge.domain.enums.SortDirection;
import com.behsazan.schemaforge.domain.model.CheckConstraint;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.model.DatabaseSchema;
import com.behsazan.schemaforge.domain.model.ForeignKey;
import com.behsazan.schemaforge.domain.model.Index;
import com.behsazan.schemaforge.domain.model.IndexColumn;
import com.behsazan.schemaforge.domain.model.PrimaryKey;
import com.behsazan.schemaforge.domain.model.Sequence;
import com.behsazan.schemaforge.domain.model.Table;
import com.behsazan.schemaforge.domain.model.UniqueKey;
import com.behsazan.schemaforge.domain.valueobject.DataType;
import com.behsazan.schemaforge.domain.valueobject.DefaultValue;
import com.behsazan.schemaforge.domain.valueobject.Description;
import com.behsazan.schemaforge.domain.valueobject.Identifier;
import com.behsazan.schemaforge.domain.valueobject.QualifiedName;
import com.behsazan.schemaforge.generation.DdlGenerator;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** R7.10 P1 core DDL acceptance for Db2 LUW as an independent sixth platform. */
class Db2LuwDdlGeneratorTest {

    @Test
    void generatesCoreDb2LuwDdlFromCanonicalModel() {
        Column id = new Column(Identifier.of("CUSTOMER_ID"), DataType.numeric("NUMBER", 18, 0),
                false, null, new Description("Customer identifier"), true, 1);
        Column code = new Column(Identifier.of("CUSTOMER_CODE"), DataType.varchar("VARCHAR2", 30),
                false, null, new Description("Customer code"), false, 2);
        Column status = new Column(Identifier.of("STATUS"), DataType.numeric("NUMBER", 1, 0),
                false, new DefaultValue("1"), new Description("Status"), false, 3);
        Column createdAt = new Column(Identifier.of("CREATED_AT"), DataType.simple("DATE"),
                false, new DefaultValue("SYSDATE"), new Description("Creation time"), false, 4);
        Column effectiveStatus = new Column(Identifier.of("EFFECTIVE_STATUS"), DataType.numeric("NUMBER", 1, 0),
                true, null, Description.empty(), false, 5, "NVL(STATUS, 0)");

        Index statusIndex = new Index(
                Identifier.of("IDX_CUSTOMERS_STATUS"),
                List.of(new IndexColumn(Identifier.of("STATUS"), SortDirection.DESC)),
                IndexType.NORMAL,
                Description.empty(),
                List.of(),
                null,
                Map.of("INDEX_TABLESPACE", "APP_IDX_TS"));

        Table table = Table.builder("BIM", "CUSTOMERS")
                .description("Customer master")
                .addColumn(id)
                .addColumn(code)
                .addColumn(status)
                .addColumn(createdAt)
                .addColumn(effectiveStatus)
                .primaryKey(new PrimaryKey(Identifier.of("PK_CUSTOMERS"), List.of(Identifier.of("CUSTOMER_ID"))))
                .addUniqueKey(new UniqueKey(Identifier.of("UK_CUSTOMERS_CODE"), List.of(Identifier.of("CUSTOMER_CODE"))))
                .addCheck(new CheckConstraint(Identifier.of("CHK_CUSTOMERS_STATUS"), "STATUS IN (0, 1)"))
                .addForeignKey(new ForeignKey(Identifier.of("FK_CUSTOMERS_BRANCH"),
                        List.of(Identifier.of("CUSTOMER_ID")), QualifiedName.of("BIM", "BRANCHES"),
                        List.of(Identifier.of("BRANCH_ID")), ReferentialAction.CASCADE, ReferentialAction.NO_ACTION))
                .addIndex(statusIndex)
                .physicalOption("TABLESPACE", "APP_TS")
                .physicalOption("GRANTS", "SELECT, INSERT, UPDATE, DELETE TO U_DEVELOPER")
                .build();

        DatabaseSchema schema = DatabaseSchema.builder("BIM")
                .metadata("sourceFile", "CUSTOMERS.docx")
                .addSequence(new Sequence(QualifiedName.of("BIM", "SEQ_CUSTOMERS"), 1, 1,
                        null, null, false, 0, Description.empty()))
                .addTable(table)
                .build();

        String sql = new DdlGenerator(new Db2LuwDialect()).generate(schema);

        assertTrue(sql.contains("SchemaForge Offline Db2 LUW DDL"));
        assertTrue(sql.contains("[INFRASTRUCTURE TEMPLATE][DB2/LUW]"));
        assertTrue(sql.contains("CREATE SCHEMA BIM"));
        assertTrue(sql.contains("CREATE SEQUENCE BIM.SEQ_CUSTOMERS START WITH 1 INCREMENT BY 1 NO CACHE NO CYCLE;"));
        assertTrue(sql.contains("CUSTOMER_ID DECIMAL(18,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(sql.contains("CUSTOMER_CODE VARCHAR(30) NOT NULL"));
        assertFalse(sql.contains("FOR MIXED DATA"));
        assertTrue(sql.contains("CREATED_AT TIMESTAMP(0) WITH DEFAULT CURRENT TIMESTAMP(0) NOT NULL"));
        assertTrue(sql.contains("EFFECTIVE_STATUS DECIMAL(1,0) GENERATED ALWAYS AS (COALESCE(STATUS, 0))"));
        assertTrue(sql.contains("CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)"));
        assertTrue(sql.contains("IN APP_TS;"));
        assertTrue(sql.contains("ADD CONSTRAINT UK_CUSTOMERS_CODE UNIQUE(CUSTOMER_CODE);"));
        assertTrue(sql.contains("CHECK(STATUS IN (0, 1));"));
        assertTrue(sql.contains("REFERENCES BIM.BRANCHES(BRANCH_ID) ON DELETE CASCADE;"));
        assertTrue(sql.contains("CREATE INDEX BIM.IDX_CUSTOMERS_STATUS ON BIM.CUSTOMERS(STATUS DESC)"));
        assertTrue(sql.contains("IN APP_IDX_TS;"));
        assertTrue(sql.contains("COMMENT ON TABLE BIM.CUSTOMERS IS 'Customer master';"));
        assertTrue(sql.contains("COMMENT ON COLUMN BIM.CUSTOMERS.CUSTOMER_CODE IS 'Customer code';"));
        assertTrue(sql.contains("GRANT SELECT, INSERT, UPDATE, DELETE ON BIM.CUSTOMERS TO U_DEVELOPER;"));
        assertFalse(sql.contains("PK_CUSTOMERS_IX"));
        assertFalse(sql.contains("UK_CUSTOMERS_CODE_IX"));
        assertTrue(sql.contains("Dialect      : Db2Luw"));
    }

    @Test
    void doesNotEmitInvalidSequenceNextValueAsColumnDefault() {
        Column id = new Column(Identifier.of("ID"), DataType.numeric("NUMBER", 9, 0),
                false, new DefaultValue("BIM.SEQ_DOC.NEXTVAL"),
                new Description("Document sequence-backed identifier"), false, 1);
        Table table = Table.builder("BIM", "DOC_TABLE")
                .addColumn(id)
                .primaryKey(new PrimaryKey(Identifier.of("PK_DOC_TABLE"), List.of(Identifier.of("ID"))))
                .build();
        DatabaseSchema schema = DatabaseSchema.builder("BIM")
                .addSequence(new Sequence(QualifiedName.of("BIM", "SEQ_DOC"), 1, 1,
                        null, null, false, 0, Description.empty()))
                .addTable(table)
                .build();

        String sql = new DdlGenerator(new Db2LuwDialect()).generate(schema);

        assertTrue(sql.contains("CREATE SEQUENCE BIM.SEQ_DOC"));
        assertTrue(sql.contains("[DB2/LUW DEFAULT REVIEW][DB2LUW-SEQ-DEFAULT-001]"));
        assertTrue(sql.contains("NEXT VALUE FOR BIM.SEQ_DOC"));
        assertFalse(sql.contains("WITH DEFAULT NEXT VALUE FOR BIM.SEQ_DOC"));
        assertFalse(sql.contains("DEFAULT NEXT VALUE FOR BIM.SEQ_DOC"));
    }

    @Test
    void mapsIdentityWithLegacySequenceDefaultToNativeIdentity() {
        Column id = new Column(Identifier.of("ID"), DataType.numeric("NUMBER", 9, 0),
                false, new DefaultValue("BIM.SEQ_ID.NEXTVAL"),
                new Description("Legacy logical identity"), true, 1);
        Table table = Table.builder("BIM", "IDENTITY_TABLE")
                .addColumn(id)
                .primaryKey(new PrimaryKey(Identifier.of("PK_IDENTITY_TABLE"), List.of(Identifier.of("ID"))))
                .build();
        DatabaseSchema schema = DatabaseSchema.builder("BIM")
                .addSequence(new Sequence(QualifiedName.of("BIM", "SEQ_ID"), 1, 1,
                        null, null, false, 0, Description.empty()))
                .addTable(table)
                .build();

        String sql = new DdlGenerator(new Db2LuwDialect()).generate(schema);

        assertTrue(sql.contains("ID DECIMAL(9,0) GENERATED BY DEFAULT AS IDENTITY"));
        assertTrue(sql.contains("[DB2/LUW IDENTITY ADAPTATION][DB2LUW-SEQ-DEFAULT-002]"));
        assertFalse(sql.contains("WITH DEFAULT NEXT VALUE FOR BIM.SEQ_ID"));
    }

    @Test
    void appliesOnlyReferentialActionsSupportedByDb2Luw() {
        Db2LuwDialect dialect = new Db2LuwDialect();

        assertTrue(dialect.referentialActionClause("ON DELETE", ReferentialAction.CASCADE)
                .contains("ON DELETE CASCADE"));
        assertTrue(dialect.referentialActionClause("ON DELETE", ReferentialAction.SET_NULL)
                .contains("ON DELETE SET NULL"));
        assertTrue(dialect.referentialActionClause("ON UPDATE", ReferentialAction.RESTRICT)
                .contains("ON UPDATE RESTRICT"));
        assertThrows(UnsupportedOperationException.class,
                () -> dialect.referentialActionClause("ON UPDATE", ReferentialAction.CASCADE));
        assertThrows(UnsupportedOperationException.class,
                () -> dialect.referentialActionClause("ON DELETE", ReferentialAction.SET_DEFAULT));
    }
}
