package com.behsazan.schemaforge;

import com.behsazan.schemaforge.dialect.db2zos.Db2ZosDialect;
import com.behsazan.schemaforge.domain.enums.IndexType;
import com.behsazan.schemaforge.domain.enums.ReferentialAction;
import com.behsazan.schemaforge.domain.enums.SortDirection;
import com.behsazan.schemaforge.domain.model.CheckConstraint;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.model.DatabaseSchema;
import com.behsazan.schemaforge.domain.model.ForeignKey;
import com.behsazan.schemaforge.domain.model.Index;
import com.behsazan.schemaforge.domain.model.IndexColumn;
import com.behsazan.schemaforge.domain.model.PrimaryKey;
import com.behsazan.schemaforge.domain.model.Sequence;
import com.behsazan.schemaforge.domain.model.Table;
import com.behsazan.schemaforge.domain.model.UniqueKey;
import com.behsazan.schemaforge.domain.valueobject.DataType;
import com.behsazan.schemaforge.domain.valueobject.DefaultValue;
import com.behsazan.schemaforge.domain.valueobject.Description;
import com.behsazan.schemaforge.domain.valueobject.Identifier;
import com.behsazan.schemaforge.domain.valueobject.QualifiedName;
import com.behsazan.schemaforge.generation.DdlGenerator;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Protects the first complete Db2 for z/OS DDL generation path. */
class Db2ZosDdlGeneratorTest {

    @Test
    void shouldGenerateCoreDb2ZosDdlFromCanonicalModel() {
        Column id = new Column(Identifier.of("CUSTOMER_ID"), DataType.numeric("NUMBER", 18, 0),
                false, null, new Description("Customer identifier"), true, 1);
        Column code = new Column(Identifier.of("CUSTOMER_CODE"), DataType.varchar("VARCHAR2", 30),
                false, null, new Description("Customer code"), false, 2);
        Column status = new Column(Identifier.of("STATUS"), DataType.numeric("NUMBER", 1, 0),
                false, new DefaultValue("1"), new Description("Status"), false, 3);
        Column createdAt = new Column(Identifier.of("CREATED_AT"), DataType.simple("DATE"),
                false, new DefaultValue("SYSDATE"), new Description("Creation time"), false, 4);
        Column externalId = new Column(Identifier.of("EXTERNAL_ID"), DataType.numeric("NUMBER", 18, 0),
                false, new DefaultValue("BIM.SEQ_CUSTOMERS.NEXTVAL"), Description.empty(), false, 5);
        Column effectiveStatus = new Column(Identifier.of("EFFECTIVE_STATUS"), DataType.numeric("NUMBER", 1, 0),
                true, null, Description.empty(), false, 6, "NVL(STATUS, 0)");

        Table table = Table.builder("BIM", "CUSTOMERS")
                .description("Customer master")
                .addColumn(id)
                .addColumn(code)
                .addColumn(status)
                .addColumn(createdAt)
                .addColumn(externalId)
                .addColumn(effectiveStatus)
                .primaryKey(new PrimaryKey(Identifier.of("PK_CUSTOMERS"), List.of(Identifier.of("CUSTOMER_ID"))))
                .addUniqueKey(new UniqueKey(Identifier.of("UK_CUSTOMERS_CODE"), List.of(Identifier.of("CUSTOMER_CODE"))))
                .addCheck(new CheckConstraint(Identifier.of("CHK_CUSTOMERS_STATUS"), "STATUS IN (0, 1)"))
                .addForeignKey(new ForeignKey(Identifier.of("FK_CUSTOMERS_BRANCH"),
                        List.of(Identifier.of("CUSTOMER_ID")), QualifiedName.of("BIM", "BRANCHES"),
                        List.of(Identifier.of("BRANCH_ID")), ReferentialAction.CASCADE, ReferentialAction.NO_ACTION))
                .addIndex(new Index(Identifier.of("IDX_CUSTOMERS_STATUS"),
                        List.of(new IndexColumn(Identifier.of("STATUS"), SortDirection.DESC)),
                        IndexType.NORMAL, Description.empty()))
                .physicalOption("TABLESPACE", "APPDB.APP_TS")
                .physicalOption("GRANTS", "SELECT, INSERT, UPDATE, DELETE TO U_DEVELOPER")
                .build();

        DatabaseSchema schema = DatabaseSchema.builder("BIM")
                .metadata("sourceFile", "CUSTOMERS.docx")
                .addSequence(new Sequence(QualifiedName.of("BIM", "SEQ_CUSTOMERS"), 1, 1,
                        null, null, false, 0, Description.empty()))
                .addTable(table)
                .build();

        String sql = new DdlGenerator(new Db2ZosDialect()).generate(schema);

        assertTrue(sql.contains("SchemaForge Offline Db2 for z/OS DDL"));
        assertTrue(sql.contains("DSNHSP template: CREATE SCHEMA AUTHORIZATION BIM"));
        assertTrue(sql.contains("CREATE SEQUENCE BIM.SEQ_CUSTOMERS START WITH 1 INCREMENT BY 1 NO CACHE NO CYCLE;"));
        assertTrue(sql.contains("CUSTOMER_ID DECIMAL(18,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(sql.contains("CUSTOMER_CODE VARCHAR(30) FOR MIXED DATA NOT NULL"));
        assertTrue(sql.contains("CREATED_AT TIMESTAMP(0) WITH DEFAULT CURRENT TIMESTAMP(0) NOT NULL"));
        assertTrue(sql.contains("EXTERNAL_ID DECIMAL(18,0) WITH DEFAULT NEXT VALUE FOR BIM.SEQ_CUSTOMERS NOT NULL"));
        assertTrue(sql.contains("EFFECTIVE_STATUS DECIMAL(1,0) GENERATED ALWAYS AS (COALESCE(STATUS, 0))"));
        assertTrue(sql.contains("CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)"));
        assertTrue(sql.contains("CREATE UNIQUE INDEX BIM.PK_CUSTOMERS_IX ON BIM.CUSTOMERS(CUSTOMER_ID)"));
        assertTrue(sql.contains("-- DB2/ZOS INDEX PHYSICAL OPTIONS"));
        assertTrue(sql.contains("FREEPAGE 0"));
        assertTrue(sql.contains("PCTFREE 10"));
        assertTrue(sql.contains(") IN APPDB.APP_TS"));
        assertTrue(sql.contains("-- DB2/ZOS TABLE PHYSICAL OPTIONS"));
        assertTrue(sql.contains("ADD CONSTRAINT UK_CUSTOMERS_CODE UNIQUE(CUSTOMER_CODE);"));
        assertTrue(sql.contains("CREATE UNIQUE INDEX BIM.UK_CUSTOMERS_CODE_IX ON BIM.CUSTOMERS(CUSTOMER_CODE)"));
        assertTrue(sql.contains("<PADDED_OR_NOT_PADDED>"));
        assertTrue(sql.contains("CHECK(STATUS IN (0, 1));"));
        assertTrue(sql.contains("REFERENCES BIM.BRANCHES(BRANCH_ID) ON DELETE CASCADE;"));
        assertTrue(sql.contains("CREATE INDEX BIM.IDX_CUSTOMERS_STATUS ON BIM.CUSTOMERS(STATUS DESC)"));
        assertTrue(sql.contains("COMMENT ON TABLE BIM.CUSTOMERS IS 'Customer master';"));
        assertTrue(sql.contains("COMMENT ON COLUMN BIM.CUSTOMERS.CUSTOMER_CODE IS 'Customer code';"));
        assertTrue(sql.contains("GRANT SELECT, INSERT, UPDATE, DELETE ON BIM.CUSTOMERS TO U_DEVELOPER;"));
        assertTrue(sql.contains("Dialect      : Db2Zos"));
        assertFalse(sql.contains("TABLESPACE APP_TS"));
        assertFalse(sql.contains("PROMPT "));
        assertFalse(sql.contains("\\set ON_ERROR_STOP"));
    }

    @Test
    void shouldApplyOnlyReferentialActionsSupportedByDb2Zos() {
        Db2ZosDialect dialect = new Db2ZosDialect();

        assertEquals(" ON DELETE CASCADE",
                dialect.referentialActionClause("ON DELETE", ReferentialAction.CASCADE));
        assertEquals(" ON DELETE SET NULL",
                dialect.referentialActionClause("ON DELETE", ReferentialAction.SET_NULL));
        assertEquals("",
                dialect.referentialActionClause("ON UPDATE", ReferentialAction.RESTRICT));
        assertThrows(UnsupportedOperationException.class,
                () -> dialect.referentialActionClause("ON UPDATE", ReferentialAction.CASCADE));
        assertThrows(UnsupportedOperationException.class,
                () -> dialect.referentialActionClause("ON DELETE", ReferentialAction.SET_DEFAULT));
    }

}
