package com.behsazan.schemaforge;

import com.behsazan.schemaforge.dialect.postgresql.PostgreSqlDialect;
import com.behsazan.schemaforge.domain.enums.IndexType;
import com.behsazan.schemaforge.domain.enums.ReferentialAction;
import com.behsazan.schemaforge.domain.enums.SortDirection;
import com.behsazan.schemaforge.domain.model.Column;
import com.behsazan.schemaforge.domain.model.DatabaseSchema;
import com.behsazan.schemaforge.domain.model.ForeignKey;
import com.behsazan.schemaforge.domain.model.Index;
import com.behsazan.schemaforge.domain.model.IndexColumn;
import com.behsazan.schemaforge.domain.model.PrimaryKey;
import com.behsazan.schemaforge.domain.model.Table;
import com.behsazan.schemaforge.domain.model.UniqueKey;
import com.behsazan.schemaforge.domain.valueobject.DataType;
import com.behsazan.schemaforge.domain.valueobject.DefaultValue;
import com.behsazan.schemaforge.domain.valueobject.Description;
import com.behsazan.schemaforge.domain.valueobject.Identifier;
import com.behsazan.schemaforge.domain.valueobject.QualifiedName;
import com.behsazan.schemaforge.generation.DdlGenerator;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgreSqlFeatureParityTest {

    @Test
    void shouldGenerateIdentityGeneratedColumnAdvancedIndexesAndDeferrableConstraints() {
        Column id = new Column(Identifier.of("ORDER_ID"), DataType.numeric("NUMBER", 18, 0),
                false, null, Description.empty(), true, 1);
        Column customerId = new Column(Identifier.of("CUSTOMER_ID"), DataType.numeric("NUMBER", 18, 0),
                false, null, Description.empty(), false, 2);
        Column reference = new Column(Identifier.of("REFERENCE_CODE"), DataType.varchar("VARCHAR2", 40),
                false, null, Description.empty(), false, 3);
        Column status = new Column(Identifier.of("STATUS"), DataType.varchar("VARCHAR2", 20),
                false, new DefaultValue("'OPEN'"), Description.empty(), false, 4);
        Column amount = new Column(Identifier.of("AMOUNT"), DataType.numeric("NUMBER", 18, 2),
                false, null, Description.empty(), false, 5);
        Column tax = new Column(Identifier.of("TAX_AMOUNT"), DataType.numeric("NUMBER", 18, 2),
                false, null, Description.empty(), false, 6);
        Column total = new Column(Identifier.of("TOTAL_AMOUNT"), DataType.numeric("NUMBER", 18, 2),
                true, null, Description.empty(), false, 7, "AMOUNT + TAX_AMOUNT");

        Table table = Table.builder("BIM", "ORDERS")
                .addColumn(id)
                .addColumn(customerId)
                .addColumn(reference)
                .addColumn(status)
                .addColumn(amount)
                .addColumn(tax)
                .addColumn(total)
                .primaryKey(new PrimaryKey(Identifier.of("PK_ORDERS"),
                        List.of(Identifier.of("ORDER_ID")), true, false))
                .addUniqueKey(new UniqueKey(Identifier.of("UK_ORDERS_REFERENCE"),
                        List.of(Identifier.of("REFERENCE_CODE")), true, true))
                .addForeignKey(new ForeignKey(Identifier.of("FK_ORDERS_CUSTOMER"),
                        List.of(Identifier.of("CUSTOMER_ID")), QualifiedName.of("BIM", "CUSTOMERS"),
                        List.of(Identifier.of("CUSTOMER_ID")), ReferentialAction.NO_ACTION,
                        ReferentialAction.NO_ACTION, true, true))
                .addIndex(new Index(Identifier.of("IDX_ORDERS_ACTIVE_CUSTOMER"),
                        List.of(new IndexColumn(Identifier.of("CUSTOMER_ID"), SortDirection.ASC)),
                        IndexType.NORMAL, Description.empty(),
                        List.of(Identifier.of("REFERENCE_CODE"), Identifier.of("TOTAL_AMOUNT")),
                        "STATUS = 'OPEN'"))
                .addIndex(new Index(Identifier.of("IDX_ORDERS_REFERENCE_LOWER"),
                        List.of(IndexColumn.expression("LOWER(REFERENCE_CODE)")),
                        IndexType.NORMAL, Description.empty()))
                .physicalOption("INDEX_TABLESPACE", "ITS_BIM")
                .build();

        String sql = new DdlGenerator(new PostgreSqlDialect()).generate(
                DatabaseSchema.builder("BIM").addTable(table).build());

        assertTrue(sql.contains("order_id NUMERIC(18,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(sql.contains("total_amount NUMERIC(18,2) GENERATED ALWAYS AS (AMOUNT + TAX_AMOUNT) STORED"));
        assertTrue(sql.contains("PRIMARY KEY (order_id) USING INDEX TABLESPACE its_bim DEFERRABLE INITIALLY IMMEDIATE"));
        assertTrue(sql.contains("UNIQUE(reference_code) USING INDEX TABLESPACE its_bim DEFERRABLE INITIALLY DEFERRED;"));
        assertTrue(sql.contains("REFERENCES bim.customers(customer_id) DEFERRABLE INITIALLY DEFERRED;"));
        assertTrue(sql.contains("CREATE INDEX bim.idx_orders_active_customer ON bim.orders(customer_id) INCLUDE (reference_code,total_amount) TABLESPACE its_bim WHERE STATUS = 'OPEN';"));
        assertTrue(sql.contains("CREATE INDEX bim.idx_orders_reference_lower ON bim.orders((LOWER(REFERENCE_CODE))) TABLESPACE its_bim;"));
    }
}
