package com.behsazan.schemaforge;

import com.behsazan.schemaforge.generation.DdlGenerator;
import com.behsazan.schemaforge.dialect.postgresql.PostgreSqlDialect;

import com.behsazan.schemaforge.domain.enums.IndexType;
import com.behsazan.schemaforge.domain.enums.ReferentialAction;
import com.behsazan.schemaforge.domain.enums.SortDirection;
import com.behsazan.schemaforge.domain.model.*;
import com.behsazan.schemaforge.domain.valueobject.*;
import org.junit.jupiter.api.Test;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Verifies the behavior and regression expectations of Postgre SQL DDL Generator.
 *
 * <p>This test documents expected behavior and protects against regression.</p>
 *
 * @since 4.1
 */
class PostgreSqlDdlGeneratorTest {

    @Test
    void shouldGeneratePostgreSqlDdlFromCanonicalModel() {
        Column id = new Column(Identifier.of("CUSTOMER_ID"), DataType.numeric("NUMBER", 18, 0),
                false, null, new Description("Customer identifier"), true, 1);
        Column code = new Column(Identifier.of("CUSTOMER_CODE"), DataType.varchar("VARCHAR2", 30),
                false, null, new Description("Customer code"), false, 2);
        Column status = new Column(Identifier.of("STATUS"), DataType.numeric("NUMBER", 1, 0),
                false, new DefaultValue("1"), new Description("Status"), false, 3);
        Column createdAt = new Column(Identifier.of("CREATED_AT"), DataType.simple("DATE"),
                false, new DefaultValue("SYSDATE"), new Description("Creation time"), false, 4);
        Column externalId = new Column(Identifier.of("EXTERNAL_ID"), DataType.numeric("NUMBER", 18, 0),
                false, new DefaultValue("BIM.SEQ_CUSTOMERS.NEXTVAL"), Description.empty(), false, 5);
        Column effectiveStatus = new Column(Identifier.of("EFFECTIVE_STATUS"), DataType.numeric("NUMBER", 1, 0),
                true, null, Description.empty(), false, 6, "NVL(STATUS, 0)");

        Table table = Table.builder("BIM", "CUSTOMERS")
                .description("Customer master")
                .addColumn(id)
                .addColumn(code)
                .addColumn(status)
                .addColumn(createdAt)
                .addColumn(externalId)
                .addColumn(effectiveStatus)
                .primaryKey(new PrimaryKey(Identifier.of("PK_CUSTOMERS"), List.of(Identifier.of("CUSTOMER_ID"))))
                .addUniqueKey(new UniqueKey(Identifier.of("UK_CUSTOMERS_CODE"), List.of(Identifier.of("CUSTOMER_CODE"))))
                .addCheck(new CheckConstraint(Identifier.of("CHK_CUSTOMERS_STATUS"), "STATUS IN (0, 1)"))
                .addForeignKey(new ForeignKey(Identifier.of("FK_CUSTOMERS_BRANCH"),
                        List.of(Identifier.of("CUSTOMER_ID")), QualifiedName.of("BIM", "BRANCHES"),
                        List.of(Identifier.of("BRANCH_ID")), ReferentialAction.CASCADE, ReferentialAction.RESTRICT))
                .addIndex(new Index(Identifier.of("IDX_CUSTOMERS_STATUS"),
                        List.of(new IndexColumn(Identifier.of("STATUS"), SortDirection.DESC)),
                        IndexType.NORMAL, Description.empty()))
                .physicalOption("TABLESPACE", "TS_BIM")
                .physicalOption("INDEX_TABLESPACE", "ITS_BIM")
                .build();

        DatabaseSchema schema = DatabaseSchema.builder("BIM")
                .metadata("sourceFile", "CUSTOMERS.docx")
                .addSequence(new Sequence(QualifiedName.of("BIM", "SEQ_CUSTOMERS"), 1, 1,
                        null, null, false, 0, Description.empty()))
                .addTable(table)
                .build();

        String sql = new DdlGenerator(new PostgreSqlDialect(), Clock.fixed(
                Instant.parse("2026-07-25T12:00:00Z"), ZoneOffset.UTC)).generate(schema);

        assertTrue(sql.contains("\\encoding UTF8"));
        assertTrue(sql.contains("\\set ON_ERROR_STOP on"));
        assertTrue(sql.contains("CREATE SCHEMA IF NOT EXISTS bim AUTHORIZATION CURRENT_USER;"));
        assertTrue(sql.contains("CREATE SEQUENCE bim.seq_customers START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;"));
        assertTrue(sql.contains("customer_id NUMERIC(18,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(sql.contains("customer_code VARCHAR(30) NOT NULL"));
        assertTrue(sql.contains("created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL"));
        assertTrue(sql.contains("external_id NUMERIC(18,0) DEFAULT nextval('bim.seq_customers') NOT NULL"));
        assertTrue(sql.contains("effective_status NUMERIC(1,0) GENERATED ALWAYS AS (COALESCE(STATUS, 0)) STORED"));
        assertTrue(sql.contains("CONSTRAINT pk_customers PRIMARY KEY (customer_id)"));
        assertTrue(sql.contains("ADD CONSTRAINT uk_customers_code UNIQUE(customer_code) USING INDEX TABLESPACE its_bim;"));
        assertTrue(sql.contains("CHECK(STATUS IN (0, 1));"));
        assertTrue(sql.contains("USING INDEX TABLESPACE its_bim"));
        assertTrue(sql.contains("REFERENCES bim.branches(branch_id) ON DELETE CASCADE ON UPDATE RESTRICT;"));
        assertTrue(sql.contains("CREATE INDEX idx_customers_status ON bim.customers(status DESC) TABLESPACE its_bim;"));
        assertTrue(sql.contains("COMMENT ON TABLE bim.customers IS 'Customer master';"));
        assertTrue(sql.contains("Dialect      : PostgreSql"));
        assertFalse(sql.contains("PROMPT "));
        assertFalse(sql.contains(" ENABLE;"));
        assertFalse(sql.contains("USING INDEX (CREATE UNIQUE INDEX"));
        assertFalse(sql.contains(" NOORDER"));
    }
    @Test
    void shouldGenerateCompositeConstraintsIndexesAndAllReferentialActions() {
        Column countryId = new Column(Identifier.of("COUNTRY_ID"), DataType.numeric("NUMBER", 10, 0),
                false, null, Description.empty(), false, 1);
        Column languageId = new Column(Identifier.of("LANGUAGE_ID"), DataType.numeric("NUMBER", 10, 0),
                false, null, Description.empty(), false, 2);
        Column priority = new Column(Identifier.of("PRIORITY"), DataType.numeric("NUMBER", 3, 0),
                false, new DefaultValue("0"), Description.empty(), false, 3);

        Table table = Table.builder("BIM", "COUNTRY_LANGUAGES")
                .addColumn(countryId)
                .addColumn(languageId)
                .addColumn(priority)
                .primaryKey(new PrimaryKey(Identifier.of("PK_COUNTRY_LANGUAGES"),
                        List.of(Identifier.of("COUNTRY_ID"), Identifier.of("LANGUAGE_ID"))))
                .addUniqueKey(new UniqueKey(Identifier.of("UK_COUNTRY_LANGUAGE_PRIORITY"),
                        List.of(Identifier.of("COUNTRY_ID"), Identifier.of("PRIORITY"))))
                .addForeignKey(new ForeignKey(Identifier.of("FK_COUNTRY_LANGUAGES_COUNTRY"),
                        List.of(Identifier.of("COUNTRY_ID")), QualifiedName.of("BIM", "COUNTRIES"),
                        List.of(Identifier.of("COUNTRY_ID")), ReferentialAction.SET_NULL, ReferentialAction.SET_DEFAULT))
                .addIndex(new Index(Identifier.of("IDX_COUNTRY_LANGUAGES_ORDER"),
                        List.of(
                                new IndexColumn(Identifier.of("COUNTRY_ID"), SortDirection.ASC),
                                new IndexColumn(Identifier.of("PRIORITY"), SortDirection.DESC)),
                        IndexType.UNIQUE, Description.empty()))
                .build();

        String sql = new DdlGenerator(new PostgreSqlDialect()).generate(
                DatabaseSchema.builder("BIM").addTable(table).build());

        assertTrue(sql.contains("CONSTRAINT pk_country_languages PRIMARY KEY (country_id,language_id)"));
        assertTrue(sql.contains("ADD CONSTRAINT uk_country_language_priority UNIQUE(country_id,priority);"));
        assertTrue(sql.contains("ON DELETE SET NULL ON UPDATE SET DEFAULT;"));
        assertTrue(sql.contains("CREATE UNIQUE INDEX idx_country_languages_order ON bim.country_languages(country_id,priority DESC);"));
        assertFalse(sql.contains("CREATE UNIQUE INDEX bim.idx_country_languages_order"));
    }

    @Test
    void shouldMapCheckExpressionsAndRenderPostgreSqlTablespaces() {
        Column status = new Column(Identifier.of("STATUS"), DataType.numeric("NUMBER", 1, 0),
                true, null, Description.empty(), false, 1);
        Table table = Table.builder("BIM", "STATUS_HISTORY")
                .addColumn(status)
                .primaryKey(new PrimaryKey(Identifier.of("PK_STATUS_HISTORY"), List.of(Identifier.of("STATUS"))))
                .addCheck(new CheckConstraint(Identifier.of("CHK_STATUS_DEFAULT"), "NVL(STATUS, 0) >= 0"))
                .addUniqueKey(new UniqueKey(Identifier.of("UK_STATUS_HISTORY"), List.of(Identifier.of("STATUS"))))
                .physicalOption("TABLESPACE", "TS_BIM")
                .physicalOption("INDEX_TABLESPACE", "ITS_BIM")
                .build();

        String sql = new DdlGenerator(new PostgreSqlDialect()).generate(
                DatabaseSchema.builder("BIM").addTable(table).build());

        assertTrue(sql.contains("CHECK(COALESCE(STATUS, 0) >= 0);"));
        assertTrue(sql.contains("TABLESPACE ts_bim;"));
        assertTrue(sql.contains("PRIMARY KEY (status) USING INDEX TABLESPACE its_bim"));
        assertTrue(sql.contains("UNIQUE(status) USING INDEX TABLESPACE its_bim;"));
    }

}
